apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
  name: pages
  namespace: bkgrp06-1
spec:
  ports:
    - name: pages-service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pages
  type: NodePort